CXX := i686-w64-mingw32-g++  
CXXFLAG := -g --static 

Xasm: xasm/tests/xasm_test.cpp xasm/include/*
	$(CXX) xasm/tests/xasm_test.cpp $(CXXFLAG) -o xasm/tests/xasm

Xlang: tests/ast_test.cpp include/*
	$(CXX) tests/ast_test.cpp $(CXXFLAG) -o tests/xlang

install: Xasm Xlang
	mv xasm/tests/xasm.exe build/
	mv tests/xlang.exe build/

clean: 
	rm -rf ./build/xasm* ./build/xlang*