name: Build-Linux
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: kurocha/setup-cpp@v1
    - name: Pack
      run: |
       cd ${{ github.workspace }} && git clone https://github.com/leadsoft-ware/Xlang
       cd ${{ github.workspace }}/Xlang/railgun && make install
    - uses: actions/upload-artifact@v2
      with:
        name: build-linux
        path: ${{ github.workspace }}/Xlang/railgun/build/*
