name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: kurocha/setup-cpp@v1
    - name: Pack
      run: |
       cd ${{ github.workspace }} && make xl && make xlang
       cd ${{ github.workspace }} && tar -cvf build-linux.zip ./xl ./vm/vm 
    - uses: actions/upload-artifact@v2
      with:
        name: Upload
        path: ${{ github.workspace }}/build-linux.zip
